import Image from 'next/image';
import { ArrowUpRight, ArrowRight, Heart, HandHeart, MapPin, Phone, Clock3, ShoppingBasket, Sprout, Package, Users } from 'lucide-react';
const phone = 'tel:+19855166091';
const directions = 'https://www.google.com/maps/search/?api=1&query=81605+Highway+41+Bush+LA+70431';
function Brand(){return <a className="brand" href="#home" aria-label="Bush Food Pantry home"><span className="brand-mark"><Sprout size={28} strokeWidth={1.7}/></span><span>Bush Food Pantry<small>NEIGHBORS HELPING NEIGHBORS</small></span></a>}
export default function Home(){return <>
<a href="#main" className="skip">Skip to content</a>
<div className="topbar" id="home"><div className="wrap"><span>Rooted in Bush. Here for St. Tammany Parish.</span><a href={phone}><Phone size={14}/> Have a question? (985) 516-6091 <ArrowUpRight size={14}/></a></div></div>
<header className="header"><div className="wrap nav"><Brand/><nav aria-label="Main navigation" className="links"><a href="#get-food">Get food</a><a href="#help">Give back</a><a href="#visit">Visit & contact</a><a href="#help" className="button">Lend a hand <Heart size={16}/></a></nav><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation"><a href="#get-food">Get food</a><a href="#help">Give back</a><a href="#visit">Visit & contact</a><a href={phone}>Call the pantry</a></nav></details></div></header>
<main id="main">
<section className="wrap hero" aria-labelledby="hero-heading"><div className="hero-copy"><div className="eyebrow">Bush, Louisiana · St. Tammany Parish</div><h1 id="hero-heading">Good food.<br/>Open hearts.<br/><em>Stronger together.</em></h1><p>A little help can make a big difference. Connecting our neighbors with food and support, right here in our community.</p><div className="actions"><a className="button" href="#get-food">Find food & support <ArrowRight size={18}/></a><a className="button outline" href="#help">I want to help <Heart size={17}/></a></div><div className="local-note"><MapPin size={16}/> Serving our neighbors in St. Tammany Parish</div></div><figure className="hero-photo"><Image unoptimized src="/produce.jpg" width="1800" height="1196" alt="Fresh vegetables displayed in market crates" fetchPriority="high"/><figcaption className="photo-label"><HandHeart size={35} strokeWidth={1.4}/><div><strong>Community starts<br/>with caring.</strong><span>One neighbor. One helping hand.</span></div></figcaption></figure></section>
<div className="visit-strip"><div className="wrap quick-info"><div className="info-item"><MapPin size={24}/><div><strong>Find us in Bush</strong><span>81605 Highway 41 · Bush, LA 70431</span></div></div><div className="info-item"><Clock3 size={24}/><div><strong>Planning a visit?</strong><span>Call to confirm distribution days & hours.</span></div></div><div className="info-item"><Phone size={24}/><div><strong>Let’s talk</strong><a href={phone}>(985) 516-6091 <span aria-hidden="true">↗</span></a></div></div></div></div>
<section className="wrap section" id="get-food"><div className="section-head"><div><div className="eyebrow">A helping hand, close to home</div><h2 style={{marginTop:18}}>Food for your table.<br/>Support for your family.</h2></div><p>Bush Food Pantry provides food assistance for individuals and families in St. Tammany Parish, following Second Harvest Food Bank guidelines. Here’s how to take the next step.</p></div><div className="steps"><article className="step"><span className="step-number">01 /</span><h3>Start with a conversation</h3><p>Call the pantry to ask about receiving food, current eligibility guidelines, and the next distribution.</p><a href={phone} className="text-link">Call the pantry <ArrowUpRight size={18}/></a></article><article className="step"><span className="step-number">02 /</span><h3>Get ready for your visit</h3><p>Ask what identification or household information to bring and whether registration is needed before you arrive.</p><a href="#questions" className="text-link">Common questions <ArrowRight size={18}/></a></article><article className="step"><span className="step-number">03 /</span><h3>Find your way here</h3><p>You’ll find the pantry at 81605 Highway 41 in Bush. Please confirm the day and time by phone before traveling.</p><a href={directions} target="_blank" rel="noopener noreferrer" className="text-link">Get directions <ArrowUpRight size={18}/></a></article></div></section>
<section className="community" id="help"><div className="wrap community-inner"><div><div className="eyebrow">Good neighbors make it possible</div><h2>There’s more than<br/>one way to give.</h2><p>Have time to share, food to contribute, or a group that wants to get involved? A conversation is a good place to start.</p><a href={phone} className="button yellow">Talk with us about helping <ArrowUpRight size={18}/></a></div><div><article className="help-item"><ShoppingBasket size={31} strokeWidth={1.5}/><div><h3>Share food & essentials</h3><p>Ask which food and household items are needed most, and arrange a suitable time to bring your donation.</p><a className="text-link" href={phone}>Ask about current needs <ArrowUpRight size={17}/></a></div></article><article className="help-item"><Users size={31} strokeWidth={1.5}/><div><h3>Give your time</h3><p>Interested in volunteering? Contact the pantry to learn about current opportunities and how you can lend a hand.</p><a className="text-link" href={phone}>Ask about volunteering <ArrowUpRight size={17}/></a></div></article><article className="help-item"><Package size={31} strokeWidth={1.5}/><div><h3>Bring your community together</h3><p>Connect your workplace, church, or neighborhood with the pantry before organizing a food drive or group contribution.</p><a className="text-link" href={phone}>Plan a contribution <ArrowUpRight size={17}/></a></div></article></div></div></section>
<section className="wrap section visit-grid" id="visit"><div className="address-card"><div className="eyebrow">Come see us</div><h3>A local place to turn.</h3><address>Bush Food Pantry<br/>81605 Highway 41<br/>Bush, Louisiana 70431</address><a href={directions} target="_blank" rel="noopener noreferrer" className="button">Get directions <ArrowUpRight size={18}/></a><div className="contact-row"><a href={phone}><Phone size={22}/> (985) 516-6091</a><p>Please call to confirm current hours, distribution dates, and what to bring.</p></div></div><div className="faq" id="questions"><div className="eyebrow">Before you visit</div><h2>A few helpful answers.</h2><details><summary>Who can receive food assistance?</summary><p>The parish resource guide lists food assistance for St. Tammany Parish residents under Second Harvest Food Bank guidelines. Call the pantry to discuss current eligibility for your household.</p></details><details><summary>When is food distributed?</summary><p>An older parish directory lists the first and third Monday of the month. Current hours and dates have not been confirmed, so please call (985) 516-6091 before making a trip.</p></details><details><summary>What should I bring?</summary><p>Call ahead to ask about identification, proof of residence, household information, and any registration requirements. The pantry can tell you what is needed for your visit.</p></details><details><summary>How can I make a donation?</summary><p>Contact the pantry directly to ask about accepted donations and delivery arrangements. The team can also tell you how to provide financial support.</p></details></div></section>
<section className="closing"><div className="wrap"><h2>A stronger community starts with us.</h2><a className="button" href={phone}>Connect with the pantry <ArrowUpRight size={18}/></a></div></section>
</main><footer className="wrap footer"><div className="footer-top"><div><Brand/><p style={{marginTop:17}}>Food. Dignity. A helping hand close to home.</p></div><nav className="footer-links" aria-label="Footer navigation"><a href="#get-food">Get food</a><a href="#help">Give back</a><a href="#visit">Visit & contact</a></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Bush Food Pantry · Bush, Louisiana</span><span>Information: <a href="https://www.stpgov.org/Documents/Department/Health%20and%20Human%20Service/Community%20Resources/STP%20Resource%20Guide%20June%202024.pdf" target="_blank" rel="noopener noreferrer">St. Tammany Parish resource guide</a></span></div></footer>
</>}

